cmake .. -DMYSQL_SERVER_SUFFIX=-mariadb-10.3.tmp -DCMAKE_BUILD_TYPE=Rel_CWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DBUILD_CONFIG=mysql_release -DCMAKE_C_COMPILER=/usr/local/gcc-4.7.3/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc-4.7.3/bin/g++ -DWITH_EMBEDDED_SERVER=OFF -DWITH_JEMALLOC=no -DWITH_SSL=no -DWITHOUT_MROONGA_STORAGE_ENGINE=1 -DWITHOUT_TOKUDB_STORAGE_ENGINE=1 -DWITHOUT_MARIA_STORAGE_ENGINE=1  -DWITHOUT_ARIA_STORAGE_ENGINE=1 -DWITH_NUMA=no -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_C_FLAGS="-static-libgcc"

cmake .. -DMYSQL_SERVER_SUFFIX=-tendbcluster-3.0.tmp -DCMAKE_BUILD_TYPE=Rel_CWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DBUILD_CONFIG=mysql_release -DWITH_EMBEDDED_SERVER=OFF -DWITH_JEMALLOC=no -DWITH_SSL=no -DWITHOUT_MROONGA_STORAGE_ENGINE=1 -DWITHOUT_TOKUDB_STORAGE_ENGINE=1 -DWITHOUT_MARIA_STORAGE_ENGINE=1  -DWITH_ARIA_STORAGE_ENGINE=0 -DWITH_NUMA=no -DWITH_WSREP=0


cmake .. -DMYSQL_SERVER_SUFFIX=-tendbcluster-3.0.tmp -DCMAKE_BUILD_TYPE=Rel_CWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DBUILD_CONFIG=mysql_release -DWITH_EMBEDDED_SERVER=OFF -DWITH_JEMALLOC=no -DWITH_SSL=no -DWITHOUT_MROONGA_STORAGE_ENGINE=1 -DWITHOUT_TOKUDB_STORAGE_ENGINE=1 -DWITHOUT_MARIA_STORAGE_ENGINE=1  -DWITH_ARIA_STORAGE_ENGINE=0 -DWITH_NUMA=no -DWITH_WSREP=0 -DCMAKE_C_COMPILER=/usr/local/gcc-4.7.3/bin/gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc-4.7.3/bin/g++ -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_C_FLAGS="-static-libgcc"


cmake .. -DMYSQL_SERVER_SUFFIX=-mariadb-10.3.tmp -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DBUILD_CONFIG=mysql_release  -DWITH_EMBEDDED_SERVER=OFF -DWITH_JEMALLOC=no -DWITH_SSL=no -DWITHOUT_MROONGA_STORAGE_ENGINE=1 -DWITHOUT_TOKUDB_STORAGE_ENGINE=1 -DWITHOUT_MARIA_STORAGE_ENGINE=1  -DCMAKE_BUILD_TYPE=Debug  -DWITH_NUMA=no -DWITHOUT_ARIA_STORAGE_ENGINE=1


all cmake option in config.h.cmake
